version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "8094:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_plugin_development
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_plugin_development_db
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp_plugin_development_db
      MYSQL_USER: wp_plugin_development
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_wp_plugin_development
    restart: always
    ports:
      - "8095:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  db_data: